using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace PTCOrderSite
{
    public partial class ValidateAddress : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            // Add a row to the results table
            TableRow row = new TableRow();
            TableCell cell = new TableCell();
            // Note the ctl00$body$ prefix is auto-generated by ASP.NET because we are using
            // a master page
            cell.Text = String.Format("{0}\n{1}, {2} {3}",
                Request.Form["ctl00$body$txtAddress"], Request.Form["ctl00$body$txtCity"],
                Request.Form["ctl00$body$txtState"], Request.Form["ctl00$body$txtZip"]);
            row.Cells.Add(cell);
            tblSearchResults.Rows.Add(row);
        }
    }
}